# Generated by Django 3.1.4 on 2021-01-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='Designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
