# Generated by Django 3.1.4 on 2021-01-14 19:31

from django.db import migrations, models
import django.db.models.deletion
import vms.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('re_password', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='visitor/photo', validators=[vms.validators.validate_file_extension])),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Guest', 'Guest')], max_length=50)),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.employee')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.visitor')),
            ],
        ),
    ]
