# Generated by Django 3.1.4 on 2021-01-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20210115_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.employee'),
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
